# Generated by Django 4.2.13 on 2024-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceRecognition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("record_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
