# Generated by Django 4.2.13 on 2024-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_recog_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="facerecognition", name="record_date",),
        migrations.AlterField(
            model_name="facerecognition",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
